# Variaveis de ambiente sensíveis (API keys, senhas etc) devem ser armazenadas em Secrets do Kubernetes.

# kubectl create secret generic climate-alert-secrets \
#   --namespace=climate-alert \
#   --from-literal=WAHA_API_KEY=$WAHA_API_KEY \
#   --from-literal=WAHA_PASSWORD=$WAHA_PASSWORD \
#   --from-literal=GOOGLE_CLIMATE_API_KEY=$GOOGLE_CLIMATE_API_KEY